#!/bin/bash
# NOTE: I have environment variable $GITHUB set to a directory
#       containing the psi4 and eigen source codes

# compile
g++ -fPIC -std=c++11 -I$GITHUB/psi4/obj/src/lib -I$GITHUB/psi4/src/lib -I$GITHUB/psi4/include -I$GITHUB/psi4/obj/include -I$GITHUB/psi4/obj/boost/include -I$GITHUB/eigen -I/usr/include/python2.7 -I. -c plugin_main.cc rhf/rhf.cpp rhf/integrals.cpp

# link
g++ -shared -o plugin_main.so plugin_main.o rhf.o integrals.o

# clean up
rm *.o
